apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202207160825" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      EXAS_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: exas
    secrets:
      EXAS_AMQP_URI: AgBjW/4j/xbHGkxzbXESNSxPcbi0rotWW/l69/N3mOC0B8/uIqWtdGaBF6y3kIuPmqDcgZ7XCc4NnBYIWhWIsgpUF1aydaGXApCtKjOPT5sOlKFnIc7KTSuG2cSwlkrtD08cRrI6IARR+OISJoINZDsqhwFaoZeq379NrxkqbcH/UUgHbz7Xm+abqECdPSvUww+oTcReB5FWGSEhF9EhqCft2Fza5OF7l4WuUBnMpvkAVrZIgCxCR3W3ld2R484dkUbxXcAtHIMO4xziKqOHBUwadVnZU1SNf5g/yrUN0ooUujDHzHtk6gB2d5E/vVfH2eSszx0TbRBex8i95/taS8tb4z7LL/Lu9IUZQjGWVTLYOIpwYJZXtaLaKzseaAKeCpMsb7OcGH5e2bHr3VOdgybtDBIGqXOnq87LWFbksDtArSyYTXRDaV1mLTL2KashuYnWXbGTGoOE6w9/NMAXblHAnMaTFkO/K65n/q9NI7HZ38CC4bvgYHt8s8JTl31VmzHgJD1KWpcc4NQrNfGGBBg0zgkJDR0F8JAKrYpC5rqOUZHEblijv10hQTr6yjkgLjzuLHJwOJ4SBQ5U45oAcC8/V+C/937kZc+pLDKh0azd4yWYVO2YzxP3bp7W9+MNH7ptIzSWooc0wAkX2uHKewj9GIZHbjYxioeAojsP4zwwy7OGBRyQBtMuZJT/3R3zMluPVdoUTAeb+1Ep8TnmpobPBPa5gOoUbWpj5Q+FDh4/vrinfsylw9f7UeOgQui0N21982s=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
