apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.82"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202207090733" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      EXAS_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: exas
    secrets:
      EXAS_AMQP_URI: AgA3+wkZghVVdQFMe5Ppe9NoU8pJ6dduzuVc/JZGU0TL9whpVZV9tUWxuptjZkIgMMkPzUn1HxPaJnselu1lFtmouUQa04ScMNh8xyojf2DlHhziD9ZuRqLgIHhWG2BS6KBRfIMNQQSPe6P+cQQJCcKwagNp2WvKaeTDH9U7O4gzQ2xe/OwLe4uw3Kfvq0+tLcIaatRJW+7V1CMxZvtyGBQIhlG54e0A50P+KFXD/Of8mD7PmP+f+PUMFzdnIJqhXhVYUeXRnOIgE7fegEHcEji98J0obuGXBUkq+vRAoLRKg6ypyzc8XcAHkH6gOD5FEDy/vmfTF27+eFe/vFiN/eo38q3dn36Jrr0vHdsCYSD0rSrLcVDRNtfbX07TDYAIHSw2nM3yIwwf1LUqtYoB6FHSegINToMKXg8XMho96bA03c9esVLYMaxCvqjOUzDvEXK//Mwjhh6nVREMxAZVt/Tm7U502Z7OjK91vBZeseM+VK7p0qjZKvzK6ai5EcBkbC9IAE2GYNAqlmt8Tf0CvxmtMUzk54kojpolIJ6ulb104HtuHzfgNvPShEtwSP1jEAQWj04qGurnuzkod2xFOCj72Vi0JDVSGdx5KQw5aB5CVLu2aCJEavSUxKakWE5IZ8mBJNLEaMJ1sefVAYLRsnDPRXK23CpIN6vFZstqt/V/zfOLif+uSsAlZKwYnZqLWHVylAkgh5jP9iFDvsbH2AWlEktYEu28/2dtVEqsvmyIQHYBNWl4dn4PGUzB45F0GEOsSm4=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    securityContext:
      runAsGroup: 65534
      runAsUser: 65534
    autoscaling:
      enabled: false
    pprof:
      enabled: true
