apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.75"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202112041750" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_LOGGER_JSON: "true"
      EXAS_WORK_DIR: "/data"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
    secrets:
      EXAS_AMQP_URI: AgDKUh4+Do33nXhYBvgq9cphlIpLrdRFu1XjHnMD7q0IN5wPIyix0XuSfF6z9HkWzS9zuvW1wJJT1zbLrOM732relyfsezdaBJ5w5sgw7NTGBxFDhuLNLztoxt1onufqE8c47l4PUsZxr5L7KMjox95ShDuwJJDq7+WznfwYIM3IKCxCDwrlQe9LPOuTakVp2LhY2peXc1ZZLVlq8SUJ9wcr3LBXMrV40KwgTZboTsnmkzbZyrMXNXO0vRB6FJ+AbfaHC7QFEqQACC+C4Y81lJa3CxRjva1gM3t/DWKvyKIeSMqQ5sAthQmwb34I4qAGhZcP5ubQntsF6FG7Y6+h83XyOAxYa+Sa7xdFNvAcuz3V8sVsnoQ8UvNVFn2MzhXNwEWyDZ+Wkb22uAsX0iHPnXiNCE25HaP1Smmnk+zkfeq5gZhWVb4k1f5SC328Dsee5N0zc1raSIPnoLA9ZolPS8bLCc5neBjhdCzwMtBEciIUTw3eEZ7naJQIPSQhkIEguGXbGwOc4Mz4iq+QahT6QbhZY0n5cJ7zWTZUaA/R3h8Cx4BiXiqc8EhNg/UwyNf/C91eSOWqPdGKFfxFWUWHl2b/pULdud6L3APKqCbqZUNlIUs0uoaQszBJXi6D9cPeJXYR6sllC0XOAT7yQvHa8q4JnbdfBW+NBuePbxLfSNGumN2XsyR9P+6+Af3PcR5tykfmZhgUuajCV4mW3PrITKDYG9xaF21nL2eaG8a2Nk5l4IdML9CoxzW3RjJL8bMSRn7esPeVgU8fI17EeTmrPZZFC4NRxvrV5aPOHgy9pkiARJfVBXV3
    securityContext:
      runAsGroup: 995
      runAsUser: 999
    autoscaling:
      enabled: false
