apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202405222349" # {"$imagepolicy": "default:flux-exas-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "exas"
      tags.datadoghq.com/version: "202405222349" # {"$imagepolicy": "default:flux-exas-api:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    strategy:
      type: Recreate
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_LOGGER_JSON: "true"
      EXAS_PPROF_AGENT: http://datadog.observability:8126
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      EXAS_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/exas
    secrets:
      EXAS_AMQP_URI: AgBXHmJI9iRMFechp/ZUYiRT4R5Us6OQ5kfqDPHxx+rmVxVAPk0x8DJaz4taHVBaCmPNUHHtYfkeOfWtf1MtroaUIWjMKQAaHnUbdmH/nSe6F4xWEEQmhEnxckdBLb6ea3euir1LRcwV4yMe6yucPbQEHH+tEi/GGx9eSsOV3+rxeg2REycqn2E5i70ry5SYVhXWbJWkvXCur7ktHoqaGKvteDnNvjyYgeD87/nOQtP5DFfSZB/Jbr0zpb5aphZBduHT9/TCQXnytckMUAMGeroTX4vgjcv1HnFWyIItsk1cXQG6zbEXoQ6kT4xDKdL2+R8sh9LnuaGHST5EV2U7TMyLLj7FLXbm+c2mcE9IdEhseuGH5DzGmxqHSr+85tvMQexy6zF6eaof+heJf4+1Xi7WcZylQaxskLqL56a3cnL1MmT3+VoiGUYJw3nV5eqiT3ZPeHoyyQBQncAAcF1ZrNAWM7GxF4Et5z31D/V4KVcFu9RNZngMLWLnXF5keGhnc70vkoJ/BMJH+REtTbuXZxMb28OEo7T99raSsM5g2qe10Mra6KieSbD0E1Zd7nlWGvyBboMBetiC4nyVLWctyDBwqId8laBKfUsby7M9SL3MebOp3Z/igfc4lg2fiOjtzgYhaSczKK7t+a84MNXF0lkXjkGYRC4Awa2QkocgJwsexl4LKUvzcQN3L4c428jL9XuE7YjRzlSplIzS8am93Zo7x8YgF4GOir7TFkWjHa7q5Wp5LwqwvYOEPVEYy7Ytpwt+
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "128Mi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
