apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.79"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202202012245" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_DIRECTORY: "/data"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
    secrets:
      EXAS_AMQP_URI: AgCTxOTpdwjrLfaaagLoU7guKsCHAhCmyRKS5WIHdVp1CYPpZOCDSewrTn2f6FOUB+czb123l0AXuhoEos4UNF2u8E5mftGzXFvTFZJtEsTHE4YzpEQ+eBFgNM0i8gGSUXZ1i5ruNgT2xVIxROQZKJo+mi3cyHPnR6gdImkctItNyhUMbzUorAerzmcZXTfJ7UZ7giVeF5OzJhDbUb3FAM9mdVgPjvGRtU5L7MAvqwvFeIIsnaG7iRNFFsLI+zTva6dOG4oDoHUPH+et8wI/8dEcTvdGAxi2o06EEIn4/JOBhoYZ6Dr7Jv+WfljJ26lnOv67xK6RrXAP8whxWBHUUA2wO6YlspbqcjSkShcetnflZWJbczNeSoybX6XpqvSJMUuNys/a7PwmnB9YakoEosniGmS0eHIl5xZyUkkn+dPphOdqF/tuor/6kFMXB9NSm66DjYqLM2hOuLMfyjHMsERvGrjvLSSsVTNTPZBiPq3LHXfDEctALy0m7ikWqJUiRkF+pg8zF78vKjZdVrXMv2qRiSwXEa7BirloCX5KFtGDgZTL7EjS9jIRtHV56+wdtEdfQrda0lKhOMvdIGx8hhYLDAasNuwnlNym9FNtB/gwbNOUEWUEeZqC+f7uy1UNT7cSiOUnSISu8wFOEybNOpvtZm+cqmU1RruWoMvJwoowKmHBDmBbgToqzvgTjShpEB0sLOTZfME5TzbKWgo2S1lmx5yEczH0ltbxE3TliEic2MjPAjUp9154j564WYy1xYKQ+N8=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
