apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.90"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202308052304" # {"$imagepolicy": "default:flux-exas-api:tag"}
    strategy:
      type: Recreate
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      GOMAXPROCS: "1"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      EXAS_TRACER_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: exas
    secrets:
      EXAS_AMQP_URI: AgCQfgwIhG73b2E1NECJknu3FePjj7yVPnOoWRt54MOdSu7Hcv+aDFuPEFI6vO6RsB0b1onsEm+RSLLf86dJHRgYtE52g3hdfxl23LPlaLECvtH7Of5BVaIexHYrpSaTFBwyMJAlpMl7WkvGk49FnyHUuZs3J8Me3SQqYuvbu2AZhFOjFF+zVwH+MmjJIUMA/SJjSZxKghHnnoOuhFyWmJA9fEuCtHNc0vwLmBa0nOAOSykiOBXnmnRYICH9VrZ517D5RFPHH96kKnjYg4DwC/s5uMdcgqw+/wv+0NYqU/QhIZ3CvjdZEpjaSvGKQEkfkFmr7F8EHCVsMwaR+QrWyTEim88IpVJcq75zqtuYBK6exC+IMMXmcB4cDGQpFf4NDgaCJ1mkghKIry4lNFWpNz1yOR6TI73XMEEvf9UAFNo/ZHaINx9kYnbT4OcxmvukExx0ln2v/2H5jYpzCQ3i4ipdX2bzHTlxJulxDn/qYZRmf9ePlu+07mCGGs5SlfJCjSbieMaSrSlECX0o4Zci7xUwZXfeuUIop/ovUUWRze+hibgX+/sW0Nj2ZzCojyjCyZHkpahIFnF6sfCa4le8DUP6JA+3Nvd4YRZYtBEL6013RZrjr06tA9jVKJuxRsQi1EipHLfSvJ6qOh6Wj+aaHCdYFPy8Y2hzLX2W/zZkxGJD5h+/qfEFLdnfR0R2MLtjgLLo+EQaSjIf2VHoPjGWA7ShDf3vHKt5sPUqSh3c/F6tJ/n0hrN8CxFUprjc2H2rDUJ9WFRy0U6oiqVcd7wdxodzoEHsZU2vLr3jxR2x3Swd+P28EgRNnJ0QNtBMY1w4jBdq/6EL5YJaA/RSmpxDKKXchG+9VDVjMm9FkA7Zg+1yZQFyb9PYpqTVplKaS5Fht7EAgN856is8Ig6uPEjkcRH+W85ICvnSwVQpETdWUlBg=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "128Mi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
