apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.79"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202202012245" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_DIRECTORY: "/data"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
    secrets:
      EXAS_AMQP_URI: AgC6ytBkZRRarwjUXDWmdN6EZMS/n4aytFg22CzQnkpERj0rwh72Y1HgL8CSm0ZJKkFXkugW4oRFeZTS2dJLh4Z2RiUZDlj/gjC/jliDbTEPmrV+KWDl1JECibJYLFjpSD88MBBt2dWU94aUOJoT88+HznN5OCjk/EngeyjcU8tR/+S7ASBNeURzu9bqS0iYytgoaWIC/BYWSnAWqR2xj12S4ZEsCIl/q6xCzFC8toQvYReUl5ui5AFUN+mHlR9qEc3VcTueroEUE+Jw/fzph0BnN97ahk3U45ytAuQrGPTHSmwFzId+S5VhU46REP3I2qhiICP6SJ6WTLxiLLvc3RALVYBZCs86IiAEM3gG4PqWdJY1BHp859UjMgQZIq8tmkgwF4WcmdzlQtk1QHX6vajMuMWRRho9BKiTu03A6UqtqYvStC3d+D616Is+q1SvEuyV+c6Ua2ZvQU2jh9FieR1c3B7WovHLEbxOU69vFUWRNYmH6NTQ6jM8a4jIr0VFi5wxF+uSGnRP4yHh9x2VipXDIc4smiLYgk/6kZYDWuF2S5hXgEG/6v59Q4PQGrGDXMzuDtYDo63olyGs3FP0J+WJqoHG3iLi2xi8VoFq5kM+Y3vezGepEF9YXoyEe4t0sxOIL3XgTiulLEo50AH7D2LzQMHiRagGVs26H2ErOsFOcCl6ZSQ01j7eCqPFl7jZ+hxA/zxWK10H2CeXqvox0zK57Hh2CM6sbFOZCjP75aPU1Q+XH2f8RdF+GBVFsn8=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
