apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.75"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202109180724" # {"$imagepolicy": "default:flux-exas-api:tag"}
    config:
      EXAS_LOGGER_JSON: "true"
