apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.79"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202202012245" # {"$imagepolicy": "default:flux-exas-api:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_DIRECTORY: "/data"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
    secrets:
      EXAS_AMQP_URI: AgAaDvvCBbemv0arN5QAvcsLCgFkTkb5Z6v8we1950CngxeQ77ZKrYUUtJbWHiCtLYNId8QFflkyJvVMkEcGRm8JxKsqhTbH9yq1q+Mlch1KZElnfp1TJRrfgwTmaGmi7BXpQUrYxTuRHy7Mtb3qgqADPjW7HHUpmrjS4ex7jYWTPhOxcM6UHGJTLVVFhjdxl/gx/0zRLg8gVzfqwQcIsYy/v2jva2jGaCVu0uhIV9YD49i0+z/A2khijWGuWPmz0/PjOX3JOoDQM6EjmIds4Tnur9ZYdunfDXdflTObJGoxy26Ck4MNf+Yxa3bVEJzsjKz5y4iY5hDtkSEWAgPOo/Z7SC/zA8gklhPzGOv9Moe5ndkj+6nULnntZV3Yf8sw3wTc5xMRgtihXvfWFo7q85Y5mrbFXPVaGjhTyEIdkW7RbkSMR7km7MPX5pT172D18wk4utFZiSY0UtdTWEA6/4dIoprIGa1glkqHwXdR9crb8SDqi+dbesv1AG/L7LFr5/JXUbdVpgOtl9vW/Z44R065y2FI7MiIOpTatnHoUalK41wyfJL/d4bwYDcnZQLsGevwLwq6sWQ/ivdmheLbuX7ig/MQrCImCpEui4tDjwos04mpmeJtO/iGVxz6XG2bcFBQCmEDVM+E30ie6TEjSrNB2J4JUBCkSFSdeVLnqyqI+lBHLseKfuCIaAYPlUukeUpOwQ0MNBo/g5B+nWbvZwSHyxDPmSD9YpGC5bVkBKOjxr6/QaNmj25Pblb2jK0=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
