apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: exas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.90"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: exas
    image:
      name: vibioh/exas
      tag: "202308052304" # {"$imagepolicy": "default:flux-exas-api:tag"}
    strategy:
      type: Recreate
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: exas
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      GOMAXPROCS: "1"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_LOGGER_JSON: "true"
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      EXAS_TRACER_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: exas
    secrets:
      EXAS_AMQP_URI: AgArZgkfTP9kheImTjMCOR9GmuOftnrR3O24TWO7rR3wuILhmhJp3LlVIxBBnDf++V1eoy2lztHW/ocP3kqC4VigbpngdsgbfI82cvitDOfilhQ9u1RmnuUApXy+DgzRna/4BagboWQ8MouNuFaWRzjDTwaY03zdaJFaG2yzpDiYI9z4Ig2peNWwufJz94uwRUcH6bBaev6lwcdkOXB+rKV5wc/aH1o05zFK/myvvVUg+ES5JH9Z/sentXiFIYERCE6NuURVypJDLN+2z4fuvxCz7/b55+v6kvRn1ELDxi+BEJwFUNG5KttEmgFb9qnVfZPBPwZgaqpqxmyJqwxiA+fbe3bSUXPBAUP7d0z/C5V8VjhZ5VfkYvdVfol//Sj3Ark4x3Zn0tJrRBNdLSFL26w+i5dfi4OCsC5DP8EWiYiVA+O8ujGh4dpg3PKAzvSP4UlGuQA9hyvjDrvi+TvqP+Bi/grG3RMHfjXARti39ThjDv55h2Z/4qsZExODUfIhiw0yqcugv1+WDTBPqdpkEmU151UNW9cGPqG0rujm1Xkn8dKjjvahKjcpRGEag2/Cb+5pTO5d3P/pBmT1wCSaxVYxkuaXMn6WFRy0U6oiqVcd7wdxodzoEHsZU2vLr3jxR2x3Swd+P28EgRNnJ0QNtBMY1w4jBdq/6EL5YJaA/RSmpxDKKXchG+9VDVjMm9FkA7Zg+1yZQFyb9PYpqTVplKaS5Fht7EAgN856is8Ig6uPEjkcRH+W85ICvnSwVQpETdWUlBg=
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "128Mi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
    pprof:
      enabled: true
